version: '3.8'

services:
  go:
    build:
      dockerfile: ./build/dev/Dockerfile
      context: .
      args:
        - DEV_UID=${DEV_UID:-1000}
        - DEV_GID=${DEV_GID:-1000}
    command: /bin/sh -c "while sleep 3600; do :; done"
    user: ${DEV_UID:-1000}:${DEV_GID:-1000}
    volumes:
      - .:/home/go-user/myapp
    working_dir: /home/go-user/myapp

  app:
    build:
      dockerfile: ./build/dev/Dockerfile
      context: .
      args:
        - DEV_UID=${DEV_UID:-1000}
        - DEV_GID=${DEV_GID:-1000}
    ports:
      - 8080:80
    volumes:
      - ./:/home/go-user/myapp
    user: ${DEV_UID:-1000}:${DEV_GID:-1000}
    command:
      - "air"
      - "-c"
      - ".air.toml"
    working_dir: /home/go-user/myapp
    environment: &app_environment
      PORT: 80
      ENVIRONMENT: local
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: things
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./build/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_PASSWORD: postgres
