# https://taskfile.dev
# Run in devcontainer
version: "3"

silent: true

tasks:
  default:
    cmds:
      - task --list

  up:
    cmds:
      - build/database/reset.sh things
    desc: Launch mandatory commands for the app to be up&ready

  install:
    aliases: ["i"]
    cmds:
      - go mod download
    desc: Install the dependencies

  update:
    aliases: ["u"]
    cmds:
      - go mod tidy
    desc: Update / clean dependencies

  lint:
    aliases: ["l"]
    desc: Lint Go code
    cmds:
      - golangci-lint run

  test-integration:
    desc: Launch integration tests
    cmds:
      - build/database/reset.sh integration
      - go test -p 1 -run Integration ./...

  test-unit:
    aliases: ["t"]
    desc: Run Go tests
    cmds:
      - go test -v

  all-tests:
    aliases: ["at"]
    desc: Run all application tests
    cmds:
      - echo ""
      - echo "|--------------|"
      - echo "| Lint Go code |"
      - echo "|--------------|"
      - echo ""
      - task: lint
      - echo "✔ No linting error on Go code"
      - echo ""
      - echo "|-------------------|"
      - echo "| Run Go unit tests |"
      - echo "|-------------------|"
      - echo ""
      - task: test-unit
      - echo ""
      - echo "|--------------------------|"
      - echo "| Run Go integration tests |"
      - echo "|--------------------------|"
      - echo ""
      - task: test-integration
      - echo ""
      - echo "|----------------------|"
      - echo "| All tests successful |"
      - echo "|----------------------|"
      - echo ""
